import cover1 from "../images/1.png";
import cover2 from "../images/2.png";
import cover3 from "../images/3.png";
import cover4 from "../images/4.png";
import cover5 from "../images/5.jpg";
import cover6 from "../images/6.jpg";
import cover7 from "../images/7.jpg";
import cover8 from "../images/8.png";
import cover9 from "../images/9.jpg";
import cover10 from "../images/10.png";
import cover11 from "../images/11.jpg";
import cover12 from "../images/12.png";
import cover13 from "../images/13.jpg";
import cover14 from "../images/14.jpg";
import cover15 from "../images/15.png";

export const Books = [
  {
    title:
      "Aflliate Marketing 101 The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover1,
    subTitle:
      "The book for Dicovering Self-Secrets The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets",
    description:
      " The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. The book for Dicovering Self-Secrets. ",
    price: 93.99,
    quantity: 0,
    code: "1",
    unicodes: "1",
  },
  {
    title: "Aflliate Marketing 33",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover2,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 64.99,
    quantity: 0,
    code: "2",
    unicodes: "2",
  },
  {
    title: "Discover the Battle Self Secret",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover3,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 69.99,
    quantity: 0,
    code: "3",
    unicodes: "3",
  },
  {
    title: "Discover the Battle Self Secret",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover4,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 94.99,
    quantity: 0,
    code: "4",
    unicodes: "4",
  },

  {
    title: "Visualization",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover5,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 54.99,
    quantity: 0,
    code: "5",
    unicodes: "5",
  },
  {
    title: "Visualization",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover6,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 56.99,
    quantity: 0,
    code: "6",
    unicodes: "6",
  },
  {
    title: "Creative Power",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover7,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 89.99,
    quantity: 0,
    code: "7",
    unicodes: "7",
  },
  {
    title: "Creative Power",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover8,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 74.99,
    quantity: 0,
    code: "8",
    unicodes: "8",
  },

  {
    title: "Aflliate Marketing",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover9,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 64.99,
    quantity: 0,
    code: "9",
    unicodes: "9",
  },
  {
    title: "Aflliate Marketing",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover10,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 46.99,
    quantity: 0,
    code: "10",
    unicodes: "10",
  },
  {
    title: "DKE",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover11,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 49.99,
    quantity: 0,
    code: "11",
    unicodes: "11",
  },
  {
    title: "Landscape",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover12,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 34.99,
    quantity: 0,
    code: "12",
    unicodes: "12",
  },

  {
    title: "Recycle Fat",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover13,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 94.93,
    quantity: 0,
    code: "13",
    unicodes: "13",
  },
  {
    title: "Logo",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover14,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 44.99,
    quantity: 0,
    code: "14",
    unicodes: "14",
  },
  {
    title: "DKE",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover15,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 49.99,
    quantity: 0,
    code: "15",
    unicodes: "15",
  },
  {
    title: "Recycle Fat",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover1,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 394.99,
    quantity: 0,
    code: "16",
    unicodes: "16",
  },
  {
    title: "Logo",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover2,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 294.99,
    quantity: 0,
    code: "17",
    unicodes: "17",
  },
  {
    title: "DKE",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover3,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 19.99,
    quantity: 0,
    code: "18",
    unicodes: "18",
  },
  {
    title: "Logo",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover4,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "Book Cover Maker: Design a Book Cover Online Free Fotor",
    price: 94.99,
    quantity: 0,
    code: "19",
    unicodes: "17",
  },
  {
    title: "Bleu",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover5,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 129.99,
    quantity: 0,
    code: "20",
    unicodes: "18",
  },
  {
    title: "Bleu",
    // image: "https://edit.org/images/cat/book-covers-big-2019101610.jpg",
    image: cover6,
    subTitle: "The book for Dicovering Self-Secrets",
    description: "The book for Dicovering Self-Secrets",
    price: 10.99,
    quantity: 0,
    code: "21",
    unicodes: "19",
  },
];
